### ISSUE TITLE
Bam uploading issue in Ribbon v2

### ISSUE THREAD

**Issue by ywzhang071394** [MariaNattestad/Ribbon#109]
Hi,

Thank you for updating Ribbon to version2. I am really surprised by the new functions.
However, I found that Ribbon v2 cannot load my local bam files while they work well for v1. 
Do you have any idea for this issue? 
Also, I appreciate it if a local version of v2 can be availiable.

**Comment by MariaNattestad** [comment]
Thanks for bringing this to my attention!
It was an easy fix:
https://github.com/MariaNattestad/Ribbon/pull/112

**Comment by MariaNattestad** [comment]
Oh yes I'll make a note about your request for the local version, thanks for that too.
