### ISSUE TITLE
Report a data loading issue

### ISSUE THREAD

**Issue by ywzhang071394** [MariaNattestad/Ribbon#122]
Hi,

I uploaded my large variants BEDPE and it can be visualized in SplitThreader. However, when i turned to ribbon, it cannot appear in "large variants". Could you help to check the issue? Thank you so much!

**Comment by MariaNattestad** [comment]
I've seen this myself but could easily fix it by switching to the SplitThreader tab and back again to Ribbon. Does that work?
(Still I'll take a look soon to see if I can make it work every time without that little trick, so it's less confusing)

**Comment by ywzhang071394** [comment]
Sorry, it goes well. Maybe my browser's issue. I would like close this.
