### ISSUE TITLE
why do bam files with multiple @PG header lines have been found to have issues fetching records.

### ISSUE THREAD

**Issue by cangfengzhe** [MariaNattestad/Ribbon#16]
Ribbon is a  good tools to view SV.

Our bam was  merged by multiple small bam file with more PG header.

Why do bam files with multiple @PG header lines have been found to have issues fetching records ?

**Comment by cangfengzhe** [comment]
https://github.com/chmille4/bam.iobio.io/blob/a93eab9f565f51d90c3dac827ebba64a8abce169/js/bam.iobio.js/bam.js#L43

when the bam has many @PG (more than 500), headLen = readInt(uncba, 4), headLen >  uncba.length, so that got an error.

when remain few @PG（less than 50）， got the correct result。

**Comment by MariaNattestad** [comment]
As you point to, it's an issue with the underlying bam library, so I'm not sure why that is, but you may be able to use samtools to reheader it into something more manageable.
