### ISSUE TITLE
error loading coords file

### ISSUE THREAD

**Issue by rotifergirl** [MariaNattestad/Ribbon#17]
I am trying to load a mummer coords file produced in they way suggested, but on both the web version and the local version of ribbon, it tells me "Info: Loading a large file might take a while" and then after a few minutes the page dies. On Safari it just reloads and says "This page was reloaded due to an error" and with Chrome it says "Oh snap! Something went wrong while displaying this page"
The file is 25.1Mb and looks like this:

> 1682	1775	3	96	94	94	94.74	3862	106134	NODE_8182_length_3862_cov_69.738705	NODE_1_length_106134_cov_23.598508
> 1794	1883	2	94	90	93	93.55	3862	106134	NODE_8182_length_3862_cov_69.738705	NODE_1_length_106134_cov_23.598508
> 1837	1921	9	92	85	84	97.65	3862	106134	NODE_8182_length_3862_cov_69.738705	NODE_1_length_106134_cov_23.598508
> 498	670	9	175	173	167	79.77	692	106134	NODE_20591_length_692_cov_15.583740	NODE_1_length_106134_cov_23.598508
> 610	692	3	83	83	81	94.05	692	106134	NODE_20591_length_692_cov_15.583740	NODE_1_length_106134_cov_23.598508
> 8181	8239	14	71	59	58	94.92	20832	106134	NODE_879_length_20832_cov_22.150711	NODE_1_length_106134_cov_23.598508
> 8243	8390	95984	96131	148	148	88.67	20832	106134	NODE_879_length_20832_cov_22.150711	NODE_1_length_106134_cov_23.598508
> 2188	2263	9	84	76	76	96.10	2908	106134	NODE_9954_length_2908_cov_23.156835	NODE_1_length_106134_cov_23.598508
> 3902	3993	9	97	92	89	93.48	4062	106134	NODE_7871_length_4062_cov_21.663237	NODE_1_length_106134_cov_23.598508
> 2617	2698	9	95	82	87	93.10	3078	106134	NODE_9546_length_3078_cov_24.302233	NODE_1_length_106134_cov_23.598508
> 2928	3021	94	2	94	93	90.62	3078	106134	NODE_9546_length_3078_cov_24.302233	NODE_1_length_106134_cov_23.598508
> 1	106134	1	106134	106134	106134	100.00	106134	106134	NODE_1_length_106134_cov_23.598508	NODE_1_length_106134_cov_23.598508
> 1	10262	1	10262	10262	10262	99.96	106134	106134	NODE_1_length_106134_cov_23.598508	NODE_1_length_106134_cov_23.598508
> 

Any advice would be appreciated

**Comment by MariaNattestad** [comment]
As the warning indicates, the file is too large. You can reduce the file
size using mummer’s delta filter (I recommend -l to filter by length)
before creating the coords file.
