### ISSUE TITLE
unable to load BAM files

### ISSUE THREAD

**Issue by hd00ljy** [MariaNattestad/Ribbon#18]
I tried to load my BAM files in various ways but they all failed

Thus, to check whether or not my BAM file is problematic, I tried BAM files from example data.

The example data I examined is "Illumina detection in A649 cell line (600KB)"

And the BAM file is
http://labshare.cshl.edu/shares/schatzlab/www-data/ribbon/DRR01684_merged.chr1.bam

But I was still unable to load the BAM file

![image](https://user-images.githubusercontent.com/13775022/51507980-c5f8e080-1e36-11e9-8768-3412d5306e14.png)

**Comment by MariaNattestad** [comment]
The bam file is loading fine, you just have to choose a region to go to. See the bottom panel called "Select Position":
![screen shot 2019-01-23 at 11 10 17 am](https://user-images.githubusercontent.com/7958077/51630690-a8dc1480-1eff-11e9-956d-9d7c037ab29e.png)

**Comment by hd00ljy** [comment]
Thank you for the reply!

I followed your instruction and was able to visualize reads with the example BAM file


But I still get errors with my BAM file

The Warning message I get is
`
Warning : No header found. Are you sure this is a bam file?
`

![image](https://user-images.githubusercontent.com/13775022/51645842-5bbc7900-1fb9-11e9-94c4-f78d29b697aa.png)



And when I choose a region where one of my SVs is, it says
`
No reads in the bam file at this location
`
![image](https://user-images.githubusercontent.com/13775022/51645891-91f9f880-1fb9-11e9-8af7-3bd2e6b1f103.png)

**Comment by hd00ljy** [comment]
I figured out why my bam file was not loaded.

I removed @SQ lines except for chr1~22,X and Y and the bam file was successfully loaded.

I think it will be better if you adjust Ribbon to handle the large BAM headers,
since the human reference genome usually contains a bunch of decoy sequences.

It seems the limit for the header is around ~1500 lines and the number of header lines of BAM file mapped to hg38 reference genome from GATK reference bundle is over 3000

**Comment by MariaNattestad** [comment]
Sorry about that. This looks like a limitation of the bam library Ribbon uses from bam.iobio/BioDalliance, and unfortunately I'm not expert enough on the inner workings of that library to address this issue. Does your bam file work in http://bam.iobio.io/?

**Comment by hd00ljy** [comment]
It seems my BAM file does not work here.

![image](https://user-images.githubusercontent.com/13775022/53784849-ed74ba00-3f59-11e9-8e06-7f631a682a6d.png)



I tried with the BAM file which I removed all decoys from and I was able to upload to Ribbon.
And the results didn't show up after several hours of waiting

![image](https://user-images.githubusercontent.com/13775022/53792477-266b5980-3f6f-11e9-959c-ecf6e53e302a.png)

**Comment by MariaNattestad** [comment]
Hmm, that confirms the bam file just isn't compatible with the bam library, so there isn't much I can do on my end. Sorry about that!

**Comment by hd00ljy** [comment]
Thank you for your help in figuring out the problem!

Removing some lines of BAM header before uploading worked for me.
