### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by cssulliv** [MariaNattestad/Ribbon#28]
Hi,

I am a fairly novice coder and was installing Ribbon after installing XAMPP v7.4.3. I followed the instructions and when I executed `npm install`, I got the following error message `-bash: npm: command not found`. I am not sure where npm is supposed to be located. 

Thank you in advance for your help.

**Comment by MariaNattestad** [comment]
Sorry, I'll add that to the steps in the documentation.
See this page for installing npm: https://www.npmjs.com/get-npm
