### ISSUE TITLE
unable to view region in bam file

### ISSUE THREAD

**Issue by indapa** [MariaNattestad/Ribbon#3]
Hi Maria -

I installed Ribbon with no trouble. I'm trying to view a BAM file of PacBio reads aligned with BWA-MEM (its fairly small 1.4GB of a viral genome) I'm able to upload the BAM file and I can see the reference contig. When I type in a region (e.g. 10000). Then it hangs and I get a 'aw,snap' error in Chrome. 

I tried loading the same BAM file in iobio and I get the same error message in Chrome.  Do you have any idea what the issue might be? It seems like it can't read the BAM file for region of interest.

**Comment by MariaNattestad** [comment]
Hi, 
I have had the same problem, and from what I can tell it stems from attempting to load too much data from the bam file. The bam library probably doesn't know that it will exceed the available memory, and I have tried to preview the bam file or somehow prevent it from loading everything at once, but I can't find any ways to do this. 
From the cancer genome I usually look at, it occurs in regions with more than about 800 reads. 
Maybe in your viral genome the coverage is also very high. It may be possible to use Ribbon if you down-sample the bam file, but you can test with samtools to see how many reads it is trying to load to confirm that this is the problem first.

**Comment by indapa** [comment]
Thanks for your reply. I talked to @chmille4 about it too, since the iobio code is running under the hood for the BAM file loading. He said pretty much the same thing. I'll try downsampling the BAM because the genome is fairly small ( < 200kb) , but my coverage is ~3000x

**Comment by indapa** [comment]
Hi Maria - Yes, I downsampled the BAM and the 'aw,snap' error goes away.  Thanks for your help!
