### ISSUE TITLE
"Aw, Snap!" on Chrome

### ISSUE THREAD

**Issue by francoiskroll** [MariaNattestad/Ribbon#33]
I'm often getting the "Aw, Snap!" error message on Chrome when it's Fetching.

> Aw, Snap!
> Something went wrong while displaying this web page.
> Error code: RESULT_CODE_INVALID_CMDLINE_URL

Any tips on avoiding that?

Example case:
I'm loading a bam file (~ 400 Mb) & bai, then looking at a genomic position or clicking a variant from my vcf file, it's 'Fetching...', then crashes.

* I've checked that my file has a single `@PG` header line
* I've tried in Chrome incognito mode, if ever there was a cache issue.
* I wanted to try in Safari instead, but the file upload tool doesn't seem to display.

What am I doing wrong?

**Comment by MariaNattestad** [comment]
Hi! It's unfortunately unavoidable. It happens when Chrome runs out of memory, which happens when the piece of the bam file that is loaded into memory is too large. See issue https://github.com/MariaNattestad/Ribbon/issues/3.

**Comment by francoiskroll** [comment]
Issue #3 was helpful, thank you. I do have very high coverage; I'll try downsample first.
