### ISSUE TITLE
question about permalink configurations

### ISSUE THREAD

**Issue by sdemirci** [MariaNattestad/Ribbon#35]
Hi Maria, 

Awesome tool! Thanks for building it. 

I have a question about permalinks.  I've deployed a local copy and created a few permalinks. Then I realized that the data is available through your website http://genomeribbon.com/ too. Can you please explain how the permalink creation is configured? And, how can I delete my data that is in your servers? Also, is there a way that i can configure the permalink to write the data locally and access only locally? 

Thanks in advance, 
Cheers,
Sevgin

**Comment by MariaNattestad** [comment]
Thanks Sevgin! @robertaboukhalil has made some great updates to Ribbon in the past year, and one of them happens to be very helpful here. I'll let him explain.

**Comment by robertaboukhalil** [comment]
Thanks Maria!

@sdemirci: I deleted data from all permalinks in our data store that did not originate from `Origin` genomeribbon.com, which should include permalinks created from a local version.

To prevent this issue from happening going forward, I've also disabled creating new permalinks from anywhere other than genomeribbon.com.

**Comment by sdemirci** [comment]
That is great! Thanks a lot.
