### ISSUE TITLE
Links Not Working on Linux

### ISSUE THREAD

**Issue by taylorjtamu** [MariaNattestad/Ribbon#36]
After cloning the repository as directed, I launch index.html in Firefox and it opens up and displays the index page. However, none of the dropdown menus display and none of the navigation links go anywhere. 
I cloned the repo to my desktop (Windows 10) as well and it's behaving properly out of the box there. Links all work, dropdowns work.

Is there a requirement that I need for Linux? I didn't see anything specific listed just for running the software. Does index.html require specific permissions?

This is on Scientific Linux 7, accessing via xRDP.

**Comment by MariaNattestad** [comment]
I don't know what that could be, and there probably isn't much I can do about it given that the headers are just using basic web technologies and Bootstrap that I didn't invent, but out of curiosity:
1. Is genomeribbon.com working on Linux?
2. Is your local version working with Chrome on Linux?

**Comment by taylorjtamu** [comment]
I installed Chromium and that seems to be working on Linux. Odd that Firefox on Linux isn't working for us, but oh well as long as we can make it run.
Thanks for the help!
