### ISSUE TITLE
Fusions from Short Read Illumina Data

### ISSUE THREAD

**Issue by jennylsmith** [MariaNattestad/Ribbon#37]
Hi Maria,

Thanks for developing such a useful SV visualization tool. Is it possible to use this software  to visualize fusions from  Illumina short read RNA-seq data? 

I filtered my BAM file to include only fusion supporting reads and then uploaded the filtered BAM into the public Ribbon web server. But I can seem to visualize only one chromosome or the other in my interchromosomal fusion. I had expected to find something similar to the example of PacBio CYTH1-EIF3H fusion ribbon plot, even though my reads are obviously much much shorter. 

Looking at the same filter BAM file in IGV shows that there are spanning reads and junction supporting reads in the BAM file. So maybe I need some additional files to tell Ribbon what to visualize? 

I attached the IGV and Ribbon plot from my fusion here, and the PacBio example I was referencing. Thanks in advance!

**My Fusion in Ribbon** 
<img width="781" alt="Ribbon_my_fusion" src="https://user-images.githubusercontent.com/18451714/96910186-f2022500-1453-11eb-9d26-cd763c6aed64.png">

**My Fusion in IGV**
<img width="1151" alt="IGV_my_fusion" src="https://user-images.githubusercontent.com/18451714/96910187-f29abb80-1453-11eb-8131-d95121ae2017.png">

**PacBio Example**
<img width="753" alt="Ribbon_PacBio_Example" src="https://user-images.githubusercontent.com/18451714/96910182-f1698e80-1453-11eb-8c85-86ffa555517b.png">

**Comment by MariaNattestad** [comment]
Ribbon may not be able to find the location of the other alignments on its own from the read pairs. It uses the SA tags for long reads to find the other alignments automatically, but paired-end reads mark their partners differently.
To get it to show the regions you want, you'll probably want to load a bedpe file ([see the format here](https://bedtools.readthedocs.io/en/latest/content/general-usage.html)) under "Upload variants", which can be for all the variants you want to show or just this one, and then select the row with the pair of coordinates you want to pull up -- i.e. the same ones you were showing in IGV.

I hope that helps!
