### ISSUE TITLE
conflict with webapollo?

### ISSUE THREAD

**Issue by MichelMoser** [MariaNattestad/Ribbon#4]
Hi i would like to use ribbon to view mummer alignments but cant get it to run. 

Installed xampp and ribbon as described but get an "Object not found!" message when trying to query localhost/ribbon

I am currently running a webapollo instance on port 8085 to keep port 80 free. 

Also do i have to start xampp for using ribbon (xampp start?). I did start it but got same "Object not found!" message. 

Is there still conflicts between the appache services? 
I am not familiar with webapplications at all so could you help me? 

Thank you

**Comment by MichelMoser** [comment]
Problem solved, i was not aware of case-sensivity in the URL. 

But another

**Comment by MariaNattestad** [comment]
The coords file is a simple text file, so you can filter it however you like to show what you are most interested in. A few suggestions include removing alignments below a certain length or focusing on one or a few chromosomes at a time.
