### ISSUE TITLE
Converting  mummer alignment to bam, sam or coord-ITH  format

### ISSUE THREAD

**Issue by dieunelderilus** [MariaNattestad/Ribbon#40]
Dear Ribbon User and Developer,

What is the best way to convert the mummer alignment to bam, sam or mummer show-coords -lTH  format. I have generated  my nucmer  alignment as follow:
nucmer --prefix=s3_cart myref.fna  ../assembly.fasta 

I convert the *detlta output to *coords as follow:
show-coords -ITH s3_cart.delta > s3_cart.coords

When I upload the is *coord file on Ribbon, I still have an error message regarding the  formatting?

What is the best way I can get a ribbon compatible format with this with the nucmer or mummer output?

Cheers,
~DD

**Comment by dieunelderilus** [comment]
Hello,
 my issue is solved when I used:
show-coords -lTH s3_cart.delta > s3_cart.coords

Thank you,
Cheers

**Comment by dieunelderilus** [comment]
Hello,

My issue is solved with this following command line:
show-coords -lTH s3_cart.delta > s3_cart.coords
 I have just changed i by l
cheers,
~DDD

**Comment by MariaNattestad** [comment]
Great! Yes, that's a lower-case L, hard to see I know!
