### ISSUE TITLE
failed to load a coordinate file

### ISSUE THREAD

**Issue by wisekh6** [MariaNattestad/Ribbon#5]
Hello Maria,

I tried to upload a coordinate file (which has been attached) into Ribbon, but I have the following error message:
```
Error: The coordinates must be the same as MUMmer's show-coords -lTH. This means 11 tab-separated columns without a header:
Ref start
Ref end
Query start
Query end
Ref alignment length
Query alignment length
Percent Identity
Total reference length
Total query length
Reference name(chromosome)
Query_name
```
Would you look at my input coordinate file to see what was wrong with it?

Thank you in advance,

hoon

[nucmer.coords.zip](https://github.com/MariaNattestad/Ribbon/files/1014667/nucmer.coords.zip)

**Comment by MariaNattestad** [comment]
Ribbon only works with unix/linux endline characters. Your file contains the Windows end-line characters, which show up as ^M on the unix/linux command-line. One way to fix this is to use the text editor Sublime Text, go to View->Line Endings->Unix, then save the file and try again. 

I have done the conversion for you here, and it works in Ribbon now. 
[nucmer.coords.zip](https://github.com/MariaNattestad/Ribbon/files/1014903/nucmer.coords.zip)

**Comment by wisekh6** [comment]
Thank you so much for your quick response.
It works.
