### ISSUE TITLE
Filtering reads with multi-read settings

### ISSUE THREAD

**Issue by HannahJusten** [MariaNattestad/Ribbon#54]
Hello,

I am using ribbon to confirm a possible inversion and I am excited about the options to visualize alignments. I am looking at a bam file, where I aligned pacbio data of an individual with one inversion haplotype to a reference that carries the other inversion haplotype.
If my target region is actually an inversion I expect to find more reverse mapping reads in that region compared to other regions of the genome. I want to test if I can see this in my data and would like to filter the reads based on length to focus on the longer ones and also the reads with higher quality. But if I add filter selections in the multiread settings (eg a minimum read lengths of 10kb) under the Reads tab this selection, that doesn't change anything in the output when I click go (to fetch my target region again with this filter). Meaning all shorter reads still occur in the output and the selection goes back to the default.
Does anyone know what could be going on? Does my request maybe take too much processing power for the program? My bam file has around 80GB and I am fetching an area with a 10kb margin to see the orientation of the longer reads more clearly.  

I wanted to generate a permalink but the program currently throws an error when I try this (Error:undefined). Please let me know if I can provide any further information to the data I am working with.

![image](https://user-images.githubusercontent.com/26040767/190263354-d1cdb943-2244-49ac-8de4-a09fcb6ba720.png)

Any advice to this or in general to confirm inversions with this program is very much appreciated!
Thank you in advance!
Hannah

**Comment by MariaNattestad** [comment]
Hi Hannah

The filters don't affect what is fetched from the bam file, they are applied afterwards. So when you change the read length filter, you can actually see some reads disappearing immediately while you type the number. You don't need to re-fetch for the filters to be applied. When you do fetch new reads, many filters reset to make sure you can see all the data before inspecting deeper with the filters.

I hope that makes sense!
Maria

PS: We'll look into the permalink issue, thanks for reporting that!

**Comment by HannahJusten** [comment]
@robertaboukhalil great! This worked. Thank you so much!

**Comment by robertaboukhalil** [comment]
Awesome, great to hear that!
