### ISSUE TITLE
MUMmer does not identify regions from positive control samples

### ISSUE THREAD

**Issue by s-t-calus** [MariaNattestad/Ribbon#55]
Hello Maria, 

We are trying to use Ribbons for data analysis of viral integrations into the human genome sequence. Unfortunately, we have encountered an issue with one step of the analysis. Specifically, the MUMmer aligner is not recognizing the integration of the virus into the host genome. However, when we used an alternative program such as BLASTn, it was able to identify these regions. We used open-source data from a published article as a positive control, so those integrations exist.

I wanted to ask if you have had any experience editing the human reference genome (i.e. adding 3.2 -7kb extra sequence) for the MUMmer before and if the alignment program is the correct tool for identifying viral integration points. Any insights or suggestions you have would be greatly appreciated. Unfortunately, the authors of the aligner do not respond to the Issues section so I decided to contact you.

Thank you for your time and effort in developing Ribbons, did you consider using a different aligner prior to the visualisation of the chromosomal rearrangements or read-splitting, I found some people doing it for viral integrations.

Sincerely,
S-T-C

**Comment by MariaNattestad** [comment]
This isn't really relevant to Ribbon, so I'll close this and suggest that you use the Bioinformatics Stack Exchange instead: https://bioinformatics.stackexchange.com/.
Note that for Ribbon you can give it a BAM file, so you absolutely don't have to use MUMmer or the coords file format to use Ribbon, and in fact BAM files are better for most purposes, so maybe just look into using bwa-mem instead.
