### ISSUE TITLE
filter by typing queries in "Inspect features" section

### ISSUE THREAD

**Issue by wisekh6** [MariaNattestad/Ribbon#6]
Hello,

I uploaded 'UCSC ref gene bed file' together with my coordinate file, and tried to filter only chr22'  genes, but it does not work for me. A corresponding permanent link is:
[http://genomeribbon.com/?perma=m9haulL2HO
](http://genomeribbon.com/?perma=m9haulL2HO)

I wonder if you can let me know how was wrong with me.

Thank you again,
 
![screen shot 2017-05-19 at 12 59 13 pm](https://cloud.githubusercontent.com/assets/3599405/26258561/2aaa9c9e-3c93-11e7-803b-02c2c07ce7a2.png)

**Comment by wisekh6** [comment]
My previous message looks not clear.

I tried to type queries into text input boxes to filter queries , but nothing happened; actually, the typed text in the box disappears when I move my cursor to a next box (such as start, end, ..).

Your comment will be highly appreciated.

Thank you in advance,

**Comment by MariaNattestad** [comment]
When you hit enter or leave the text box, it tries to filter by your query. If the query is invalid, it clears it instead. 
To filter to chr22, type `=chr22` with no spaces before it or in between. 
The instructions for filtering are laid out if you load variants. Sorry I apparently forgot to add the same information to the features.

**Comment by wisekh6** [comment]
Thank you for your reply.
Now, I can filter queries, but feature information such as gene names in the "bed" file is not shown in the plot. Originally, I thought such information would show up in the plot.


Thank you,

**Comment by MariaNattestad** [comment]
How to show the gene names:
<img width="443" alt="screenshot 2017-05-19 14 40 25" src="https://cloud.githubusercontent.com/assets/7958077/26267869/26d03e54-3ca1-11e7-8d86-5e692ee0d05c.png">
It will show the NM_* names, so if you want the common gene names, just swap out the columns before you load the file. 

By the way, the table filtering is just for quick inspection and doesn't do anything to the plots. 
Filter the file yourself before loading it if you really need it.
