### ISSUE TITLE
Visualize multiple BAMs/VCFs

### ISSUE THREAD

**Issue by robertaboukhalil** [MariaNattestad/Ribbon#63]
To support tumor vs. normal comparisons, color reads differently for each BAM, with reads grouped vertically, and the bam file names on the side like in IGV

**Comment by MariaNattestad** [comment]
prefer to have file names or nicknames in the viz itself.

**Comment by robertaboukhalil** [comment]
Partly done, see https://github.com/MariaNattestad/Ribbon/issues/105 for remaining work
