### ISSUE TITLE
colors for forward and reverse alignment

### ISSUE THREAD

**Issue by wisekh6** [MariaNattestad/Ribbon#7]
Hello Maria,

I expect that forward alignments would be colored with 'blue' and reverse alignments with 'red' in "multiread view", but I found that both were colored with 'blue' in my case. 
Shown below are the single-read view for one reverse-aligned read and one forward-aligned read.
Would you let me know how to update the color setting?

Thank you in advance,

Hoon

Multiread view:
![multi](https://cloud.githubusercontent.com/assets/3599405/26429610/f0c1bb62-40b5-11e7-9b8b-90f1a6b668c8.png)

Dot plot for a reverse-aligned read:
![check](https://cloud.githubusercontent.com/assets/3599405/26429476/01e25cfe-40b5-11e7-88a4-ddb0f7733bca.png)

Dot plot for a forward aligned read:
![forward](https://cloud.githubusercontent.com/assets/3599405/26429505/3d5ee2ca-40b5-11e7-96ef-b2337b64c4c0.png)

**Comment by MariaNattestad** [comment]
Just go to the multi-read settings, reads tab, and switch the orientation to original.
A lot of things are possible if you just look around at the settings.
