### ISSUE TITLE
Ignore gaps under a customizable size

### ISSUE THREAD

**Issue by SHuang-Broad** [MariaNattestad/Ribbon#8]
Hi Maria,

First of all, thank you very much for providing Ribbon. I've found it being incredibly useful for my work in detecting complex genome rearrangements!

One feature that I think would be quite useful is to ignore the "small" gaps in long reads' alignments. This would get rid of the small indels that make the visualization a bit "too busy" for seeing the big picture ([example](http://www.genomeribbon.com/?perma=Vru9O9hznt) with 3 alignments but several small gaps).

Thanks!

Steve

**Comment by MariaNattestad** [comment]
Glad to hear you are finding Ribbon useful in your work. You may also find splitthreader.com useful for those rearrangements. 
The feature you are describing already exists: Single-read Settings" under the "settings" tab, by sliding the "Minimum indel size to split" slider to the right.
