### ISSUE TITLE
Support for CSI BAM index

### ISSUE THREAD

**Issue by nathanhaigh** [MariaNattestad/Ribbon#9]
I'm working on updating the `Ribbon` code to support the `.CSI` BAM indexing schema so I can use it with plant genomes containing chromosomes > 29^2-1 bp long.

I'm part way there already but I'm trying to figgur out what the [`BamFile.prototype.blocksForRange`](https://github.com/MariaNattestad/Ribbon/blob/master/js/bam/bam.js#L116) function is doing so I can update it to support `CSI`. Some pointers would be appreciated.

**Comment by MariaNattestad** [comment]
I believe the function searches in the index to see which blocks in the bam file it needs to load to get the entire range from min to max on the chromosome refId. The whole bam library is from https://github.com/chmille4/bam.iobio.io, so they may be better able to help with the specifics over there. 
I appreciate you working to improve the bam library Ribbon uses!
